/*
 * Copyright 2017 LinkedIn Corp. Licensed under the BSD 2-Clause License (the "License"). See License in the project root for license information.
 */
import org.gradle.util.GradleVersion

//otherwise it defaults to the folder name
rootProject.name = 'cruise-control'

include 'cruise-control', 'cruise-control-metrics-reporter', 'cruise-control-core'

def gradleVer = GradleVersion.current()
def minimumVersion = GradleVersion.version("7.2")
if (gradleVer < minimumVersion) {
  throw new GradleScriptException("this build cannot be run with gradle < " + minimumVersion + ". current detection version is " +
      gradleVer + ". use newer gradle or (better yet) use the wrapper", null)
}
